# Generated by Django 4.2.7 on 2023-11-16 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follow_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='gigs',
            field=models.ManyToManyField(blank=True, related_name='all_gigs', to='gigs.gig'),
        ),
        migrations.AddField(
            model_name='user',
            name='upcoming',
            field=models.ManyToManyField(blank=True, related_name='upcoming_gigs', to='gigs.gig'),
        ),
    ]
