# Generated by Django 4.2.7 on 2024-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Essex', max_length=300),
            preserve_default=False,
        ),
    ]
