# Generated by Django 4.2.7 on 2023-11-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='setlist',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gig',
            name='band',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gig',
            name='venue',
            field=models.CharField(max_length=500),
        ),
    ]
