# Generated by Django 4.2.7 on 2023-11-16 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_setlist_alter_gig_band_alter_gig_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='image',
            field=models.URLField(default='https://png.pngtree.com/png-clipart/20190517/original/pngtree-cartoon-kids-band-singing-elements-element-png-image_4074731.jpg', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
