# Generated by Django 4.2.7 on 2023-11-16 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_gig_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='image',
            field=models.URLField(default='https://png.pngtree.com/png-clipart/20190517/original/pngtree-cartoon-kids-band-singing-elements-element-png-image_4074731.jpg', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='gig',
            name='setlist',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
