# Generated by Django 4.2.7 on 2024-02-02 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_alter_gig_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='image',
            field=models.URLField(blank=True, default='https://w7.pngwing.com/pngs/104/393/png-transparent-musical-ensemble-musician-rock-band-angle-animals-logo-thumbnail.png', validators=[django.core.validators.URLValidator()]),
        ),
    ]
