# Generated by Django 4.2.7 on 2024-02-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_gig_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('JPY', '¥'), ('CNY', '¥'), ('AUD', '$'), ('CAD', '$'), ('CHF', 'CHF'), ('SEK', 'kr'), ('NZD', '$'), ('KRW', '₩'), ('SGD', '$'), ('NOK', 'kr'), ('MXN', '$'), ('INR', '₹'), ('RUB', '₽'), ('ZAR', 'R'), ('BRL', 'R$'), ('TRY', '₺'), ('HKD', '$'), ('IDR', 'Rp'), ('TWD', 'NT$'), ('THB', '฿'), ('PHP', '₱'), ('MYR', 'RM')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='gig',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gig',
            name='setlist',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
