# Generated by Django 4.2.7 on 2024-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_alter_gig_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='gig',
            name='support',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='gig',
            name='currency',
            field=models.CharField(blank=True, default='£', max_length=50),
        ),
        migrations.AlterField(
            model_name='gig',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gig',
            name='setlist',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
