# Generated by Django 4.2.7 on 2024-02-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_gig_notes_gig_support_alter_gig_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='currency',
            field=models.CharField(blank=True, default='$', max_length=50),
        ),
    ]
