# Generated by Django 4.2.7 on 2024-02-21 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0014_alter_gig_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='image',
            field=models.URLField(default='https://w7.pngwing.com/pngs/104/393/png-transparent-musical-ensemble-musician-rock-band-angle-animals-logo-thumbnail.png', max_length=1000, validators=[django.core.validators.URLValidator()]),
        ),
    ]
